### PR TITLE
await differently

### LINKED ISSUE #12: pnpm/pnpm release notification is failing
```
Feb 04 12:48:56 release-notifier heroku/router:  at=info method=POST path="/" host=release-notifier.herokuapp.com request_id=e5e0db52-c5dd-4a84-96a7-47f46a88cfca fwd="192.30.252.45" dyno=web.1 connect=1ms service=3ms status=200 bytes=231 protocol=https 
Feb 04 12:48:56 release-notifier app/web.1:  20:48:56.049Z  INFO probot: Webhook received 
Feb 04 12:48:56 release-notifier app/web.1:    event: { 
Feb 04 12:48:56 release-notifier app/web.1:      "id": "d1197b00-09ec-11e8-8f33-3693d81f747b", 
Feb 04 12:48:56 release-notifier app/web.1:      "event": "release.published", 
Feb 04 12:48:56 release-notifier app/web.1:      "repository": "pnpm/pnpm", 
Feb 04 12:48:56 release-notifier app/web.1:      "installation": 84166 
Feb 04 12:48:56 release-notifier app/web.1:    } 
Feb 04 12:48:56 release-notifier app/web.1:  20:48:56.050Z  INFO probot: POST / 200 - 1.80 ms (id=e5e0db52-c5dd-4a84-96a7-47f46a88cfca) 
Feb 04 12:48:56 release-notifier app/web.1:  20:48:56.067Z  INFO probot: v1.32.0 published! (id=d1197b00-09ec-11e8-8f33-3693d81f747b) 
Feb 04 12:48:56 release-notifier app/web.1:  20:48:56.190Z  INFO probot: previous release was v1.31.6 (2018-02-03T13:57:58Z) (id=d1197b00-09ec-11e8-8f33-3693d81f747b) 
Feb 04 12:48:57 release-notifier app/web.1:  20:48:57.155Z  INFO probot: commits between versions: 6 (id=d1197b00-09ec-11e8-8f33-3693d81f747b) 
Feb 04 12:48:58 release-notifier app/web.1:  20:48:58.145Z ERROR probot: 
Feb 04 12:48:58 release-notifier app/web.1:    Promise { 
Feb 04 12:48:58 release-notifier app/web.1:      <rejected> TypeError: Cannot read property 'number' of undefined 
Feb 04 12:48:58 release-notifier app/web.1:        at chain.map.compact.uniqBy.forEach (/app/index.js:66:46) 
Feb 04 12:48:58 release-notifier app/web.1:        at <anonymous> 
Feb 04 12:48:58 release-notifier app/web.1:        at process._tickDomainCallback (internal/process/next_tick.js:228:7) } 
Feb 04 12:48:58 release-notifier app/web.1:    -- 
Feb 04 12:48:58 release-notifier app/web.1:    TypeError: Cannot read property 'number' of undefined 
Feb 04 12:48:58 release-notifier app/web.1:        at chain.map.compact.uniqBy.forEach (/app/index.js:66:46) 
Feb 04 12:48:58 release-notifier app/web.1:        at <anonymous> 
Feb 04 12:48:58 release-notifier app/web.1:        at process._tickDomainCallback (internal/process/next_tick.js:228:7) 
Feb 04 13:06:16 release-notifier heroku/web.1:  Cycling 
Feb 04 13:06:16 release-notifier heroku/web.1:  State changed from up to starting 
Feb 04 13:06:16 release-notifier heroku/web.1:  Stopping all processes with SIGTERM 
```

### PR DESCRIPTION
**Pull request by zeke**
@gr2m inline-await magic is new to me. Does this change look appropriate?

Maybe fixes #12

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -63,11 +63,12 @@ async function handleRelease (robot, context) {
     .compact()
     .uniqBy('number')
     .forEach(async pullRequest => {
-      context.log(`PR: ${(await pullRequest).number}`)
+      const pr = await pullRequest
+      context.log(`PR: ${pr.number}`)
```
Comment (gr2m) [inline index.js]: we can remove line 66 altogether and just do `pullRequest.number`

Comment (zeke) [reply index.js]: ok cool. That's kinda what I thought, but then I though there was something tricky about using async code in a forEach loop...? Anyway I changed it. Gonna ship it.
